# Net Speed Test ships without reflection, serialization frameworks or JNI, so the
# default keep rules for manifest components (generated by aapt2/AGP) are sufficient.
-allowaccessmodification
-repackageclasses
-optimizationpasses 5
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute SourceFile

# Strip verbose logging from release builds.
-assumenosideeffects class android.util.Log {
    public static int v(...);
    public static int d(...);
}
